---
- name: Configure Juniper device
  juniper_junos_config:
    lines:
      - set system host-name Juniper_Device
      - set interfaces ge-0/0/0 unit 0 family inet address 192.168.1.1/24
      - set interfaces ge-0/0/1 unit 0 family inet address 192.168.2.1/24
      - commit
